//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_comment
    {
        public int id { get; set; }
        public System.DateTime created_date { get; set; }
        public string Comment { get; set; }
        public int id_user { get; set; }
        public int id_translate { get; set; }
    
        public virtual t_translate t_translate { get; set; }
        public virtual t_user t_user { get; set; }
    }
}
