//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_translate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_translate()
        {
            this.t_comment = new HashSet<t_comment>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string decription { get; set; }
        public int src_lang { get; set; }
        public int dest_lang { get; set; }
        public System.DateTime created_date { get; set; }
        public System.DateTime end_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public int translate_status { get; set; }
        public string link_customer { get; set; }
        public string link_translator { get; set; }
        public Nullable<decimal> price { get; set; }
        public int id_customer { get; set; }
        public Nullable<int> id_translator { get; set; }
        public int id_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_comment> t_comment { get; set; }
        public virtual t_language t_language { get; set; }
        public virtual t_language t_language1 { get; set; }
        public virtual t_status t_status { get; set; }
        public virtual t_user t_user { get; set; }
        public virtual t_user t_user1 { get; set; }
        public virtual t_type t_type { get; set; }
    }
}
