//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project1.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_KulakovEntities : DbContext
    {
        public db_KulakovEntities()
            : base("name=db_KulakovEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_comment> t_comment { get; set; }
        public virtual DbSet<t_language> t_language { get; set; }
        public virtual DbSet<t_position> t_position { get; set; }
        public virtual DbSet<t_status> t_status { get; set; }
        public virtual DbSet<t_translate> t_translate { get; set; }
        public virtual DbSet<t_type> t_type { get; set; }
        public virtual DbSet<t_user> t_user { get; set; }
    }
}
